# Generated by Django 4.2.4 on 2023-08-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='booking',
            name='image',
            field=models.ImageField(null=True, upload_to='menu_items/'),
        ),
    ]
