# Generated by Django 4.2.4 on 2023-08-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_options_booking_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='image',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(null=True, upload_to='menu_items/'),
        ),
    ]
